/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package muzikdosyam;

import java.util.Date;
import java.text.SimpleDateFormat;

/**
 *
 * @author YunusKARAMAN
 */
public class AnaSayfa extends javax.swing.JFrame {

    /**
     * Creates new form AnaSayfa
     */
    public AnaSayfa() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_listem = new javax.swing.JButton();
        btn_cikis = new javax.swing.JButton();
        btn_genel = new javax.swing.JButton();
        btn_ulke = new javax.swing.JButton();
        btn_Tur = new javax.swing.JButton();
        btn_liste = new javax.swing.JButton();
        btn_takip = new javax.swing.JButton();
        btn_premium = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_listem.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btn_listem.setText("Müzik Listem");
        btn_listem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listemActionPerformed(evt);
            }
        });

        btn_cikis.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btn_cikis.setText("Çıkış Yap");
        btn_cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cikisActionPerformed(evt);
            }
        });

        btn_genel.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btn_genel.setText("En Çok Dinlenen Müzikler");
        btn_genel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_genelActionPerformed(evt);
            }
        });

        btn_ulke.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btn_ulke.setText("Ülkelere Göre En Çok Dinlenen Müzikler");
        btn_ulke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ulkeActionPerformed(evt);
            }
        });

        btn_Tur.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btn_Tur.setText("Türlerine Göre En Çok Dinlenen Müzikler");
        btn_Tur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TurActionPerformed(evt);
            }
        });

        btn_liste.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btn_liste.setText("Müzik Listesi");
        btn_liste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listeActionPerformed(evt);
            }
        });

        btn_takip.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btn_takip.setText("Takip Edilenler");
        btn_takip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_takipActionPerformed(evt);
            }
        });

        btn_premium.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btn_premium.setText("Premium Kullanıcılar");
        btn_premium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_premiumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_liste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_listem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_cikis, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(btn_genel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(btn_ulke, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(btn_Tur, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(btn_takip, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(btn_premium, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btn_listem, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_liste, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_genel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Tur, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ulke, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_takip, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_premium, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_cikis, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_TurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TurActionPerformed
        TurEnCokDinlenen frm = new TurEnCokDinlenen();
        this.setVisible(false);
        frm.setVisible(true);
    }//GEN-LAST:event_btn_TurActionPerformed

    private void btn_listeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listeActionPerformed
        MuzikListesi frm = new MuzikListesi();
        this.setVisible(false);
        frm.setVisible(true);
    }//GEN-LAST:event_btn_listeActionPerformed

    private void btn_listemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listemActionPerformed
        MuzikListem frm = new MuzikListem();
        this.setVisible(false);
        frm.setVisible(true);
    }//GEN-LAST:event_btn_listemActionPerformed

    private void btn_cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cikisActionPerformed
        
        Giris frm= new Giris();
        this.setVisible(false);
        frm.setVisible(true);
        
    }//GEN-LAST:event_btn_cikisActionPerformed

    private void btn_genelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_genelActionPerformed
        EnCokDinlenen frm= new EnCokDinlenen();
        this.setVisible(false);
        frm.setVisible(true);
        
    }//GEN-LAST:event_btn_genelActionPerformed

    private void btn_ulkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ulkeActionPerformed
        UlkeEnCokDinlenen frm = new UlkeEnCokDinlenen();
        this.setVisible(false);
        frm.setVisible(true);
    }//GEN-LAST:event_btn_ulkeActionPerformed

    private void btn_takipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_takipActionPerformed
        TakipEdilen frm = new TakipEdilen();
        this.setVisible(false);
        frm.setVisible(true);
    }//GEN-LAST:event_btn_takipActionPerformed

    private void btn_premiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_premiumActionPerformed
       PremiumKullanicilar frm = new PremiumKullanicilar();
       this.setVisible(false);
       frm.setVisible(true);
    }//GEN-LAST:event_btn_premiumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaSayfa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Tur;
    private javax.swing.JButton btn_cikis;
    private javax.swing.JButton btn_genel;
    private javax.swing.JButton btn_liste;
    private javax.swing.JButton btn_listem;
    private javax.swing.JButton btn_premium;
    private javax.swing.JButton btn_takip;
    private javax.swing.JButton btn_ulke;
    // End of variables declaration//GEN-END:variables
}
